################### 开发环境数据源配置 #########################
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.96.75.175:3306/xgsb?useUnicode=true&characterEncoding=utf-8
    username: xgsb
    password: password123
