################### 正式环境数据源配置 #########################
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scpt?useUnicode=true&characterEncoding=utf-8
    username: root
    password: password123
